FROM ubuntu:14.04
MAINTAINER cikai "cikai0923@gmail.com"
# change apt sources list 
# RUN mv /etc/apt/sources.list /etc/apt/sources.list.backup
# COPY cn-ubuntu-sources.list /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y nginx
EXPOSE 80
